//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ayni.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calificacion
    {
        public int idCalificacion { get; set; }
        public Nullable<int> idUsuarioCalificado { get; set; }
        public string ComentarioCalificacion { get; set; }
        public Nullable<int> idTransaccion { get; set; }
    
        public virtual Transaccion Transaccion { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
