//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ayni.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calificacion
    {
        public int idCalificacion { get; set; }
        public Nullable<int> idUsuarioCalifica { get; set; }
        public Nullable<int> idUsuarioCalificado { get; set; }
        public string ComentarioCalificacion { get; set; }
        public Nullable<int> idTransaccion { get; set; }
        public Nullable<int> Puntaje { get; set; }
        public Nullable<int> idTipoCalificacion { get; set; }
    
        public virtual Transaccion Transaccion { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual TipoPublicacion TipoPublicacion { get; set; }
    }
}
