//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ayni.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Postulacion
    {
        public int idPostulacion { get; set; }
        public Nullable<int> idPublicacion { get; set; }
        public Nullable<int> idPostulante { get; set; }
        public Nullable<bool> Aceptado { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        public virtual Publicacion Publicacion { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
