//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ayni.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pregunta
    {
        public int idPregunta { get; set; }
        public int IdPublicacion { get; set; }
        public int idUsuario { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> idRespuesta { get; set; }
    
        public virtual Publicacion Publicacion { get; set; }
        public virtual Respuesta Respuesta { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
