//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ayni.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publicacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Publicacion()
        {
            this.Comentario = new HashSet<Comentario>();
            this.PublicacionCategoria = new HashSet<PublicacionCategoria>();
            this.Transaccion = new HashSet<Transaccion>();
        }
    
        public int idPublicacion { get; set; }
        public string Titulo { get; set; }
        public int idUsuario { get; set; }
        public int Valor { get; set; }
        public int idTipoPublicacion { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime Fecha_publicacion { get; set; }
        public System.DateTime Fecha_fin { get; set; }
        public int idEstadoPublicacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comentario> Comentario { get; set; }
        public virtual EstadoPublicacion EstadoPublicacion { get; set; }
        public virtual TipoPublicacion TipoPublicacion { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PublicacionCategoria> PublicacionCategoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaccion> Transaccion { get; set; }
    }
}
