//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ayni.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publicacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Publicacion()
        {
            this.Transaccion = new HashSet<Transaccion>();
            this.Postulacion = new HashSet<Postulacion>();
            this.Pregunta = new HashSet<Pregunta>();
        }
    
        public int idPublicacion { get; set; }
        public string Titulo { get; set; }
        public int idUsuario { get; set; }
        public int Valor { get; set; }
        public int idTipoPublicacion { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime Fecha_publicacion { get; set; }
        public Nullable<System.DateTime> Fecha_fin { get; set; }
        public int idEstadoPublicacion { get; set; }
        public Nullable<System.DateTime> Fecha_inicio { get; set; }
        public int idCategoria { get; set; }
        public string Ubicacion { get; set; }
        public string Imagen { get; set; }
    
        public virtual EstadoPublicacion EstadoPublicacion { get; set; }
        public virtual TipoPublicacion TipoPublicacion { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaccion> Transaccion { get; set; }
        public virtual Categoria Categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Postulacion> Postulacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pregunta> Pregunta { get; set; }
    }
}
