//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ayni.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Respuesta
    {
        public int idRespuesta { get; set; }
        public Nullable<int> idPregunta { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Descripcion { get; set; }
    
        public virtual Pregunta Pregunta { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
