//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ayni.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Saldo
    {
        public int IdUsuario { get; set; }
        public Nullable<int> Cantidad { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
