//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ayni.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaccion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transaccion()
        {
            this.Calificacion = new HashSet<Calificacion>();
        }
    
        public int idTransacion { get; set; }
        public int idUsuarioOfrece { get; set; }
        public int idUsuarioRecibe { get; set; }
        public int idPublicacion { get; set; }
        public int idEstadoTransaccion { get; set; }
        public Nullable<bool> confirm_ofrece { get; set; }
        public Nullable<bool> confirm_recibe { get; set; }
    
        public virtual EstadoTransaccion EstadoTransaccion { get; set; }
        public virtual Publicacion Publicacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Calificacion> Calificacion { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
